# Generated by Django 5.2 on 2025-06-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frequemcy',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Repeat pattern (daily, weekly, monthly)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='interval',
            field=models.PositiveIntegerField(default=1, help_text='Repeat every N days/weeks/months'),
        ),
    ]
