# Generated by Django 5.2 on 2025-06-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_frequemcy_task_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='frequemcy',
            new_name='frequency',
        ),
    ]
